config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  post "/travel_enquiry" => "home#travel_enquiry", :as => :travel_enquiry
  get "/contact_us" => "home#contact_us", :as => :contact_us
  get "/business_class" => "home#business_class", :as => :business_class
  get "/last_minute" => "home#last_minute", :as => :last_minute
  get "/blogs" => "home#blogs", :as => :blogs
  get "/win_cash" => "home#win_cash", :as => :win_cash
  get "/flights" => "home#flights", :as => :flights
  get "/canada_to_india" => "home#canada_to_india", :as => :canada_to_india
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :footer_list
	before_action :countries, only: [:index, :canada_to_india]

	def index
	end

	def travel_enquiry
		begin
			@trip_detail = params[:trip]

			EnquiryMailer.with(trip_detail: @trip_detail).travel_enquiry_email.deliver_now
			flash[:notice] = "Thank you #{@trip_detail[:name]} for your Inquiry! We'll get contact you soon!"
			redirect_to root_path
		rescue => e
			flash[:error] = "Error #{e.message}"
			redirect_to root_path
		end
	end

	def contact_us
	end

	def business_class
	end

	def last_minute
	end

	def blogs
	end

	def win_cash
	end

	def flights
	end

	def canada_to_india
		@canada_cities = ['ALBERTA','BRAMPTON','BRANDON','BRITISH COLUMBIA','CALGARY','EDMONTON',
			'REGINA ','SASKATCHEWAN','SASKATOON','ST JOHNS','SYDNEY','TORONTO','QUEBEC','London',
			'NOVA SCOTIA','ONTARIO','OTTAWA','FORT MCMURRAY','GRANDE PRAIRIE','HALIFAX','KELOWNA',
			'MANITOBA','MONTREAL','NEW BRUNSWICK','VICTORIA (BC)','VANCOUVER','WINNIPEG','YUKON',
			'NEWFOUNDLAND AND LABRADOR','PRINCE GEORGE (BC)','THUNDER BAY ONTARIO']
	end

	private

		def footer_list
			@destinations = ['Delhi','Mumbai','Hyderabad','Bangalore','Kolkata','Chennai','Cochin', 'Amritsar']
			@airlines = ['Qatar Airways', 'Etihad Airways', 'British Airways', 'Air India', 'Air Canada', 'United Airline',
			'Singapur Airline', 'Lufthansa']
		end

		def countries
			@source = ["Canada","Italy","Australia","Austria","America","New York",'Atlanta','Chicago','New York',
						'Dallas','Denver', 'Los Angeles','Tempa','San Diego','Charlotte','Las Vegas','Phoenix',
						'Orlando','Seattle','Miami','Houston','Fort Lauderdale','San Francisco','Minneapolis',
						'Detroit','Boston','Salt Lake City','Philadelphia','Baltimore','Nashville','Washington DC',
						'Austin','Portland','St. Louis','San Jose','Oakland','San Antonio','Kansas City',
						'Raleigh Durham','Indiana Polis','Cincinnati','Pittsburgh','Bradley']
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/_alerts.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice]%>
  </div>
<% elsif flash[:error]%>
  <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error]%>
  </div>
 <% elsif flash[:alert] %>
  <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert]%>
  </div>
<% end %>

<style type="text/css">
	.alert{
		text-align: center;
	}
  .alert-success{
    color: green;
    width: 100%;
  }
  .alert-danger{
    color: red;
    width: 100%;
  }
  .alert-warning{
    color: orange;
    width: 100%;
  }
  .alert button{
  	float: right;
  }
</style>

app/views/application/_enquiry_form.html.erb
<div class="fix-form">
  <%= form_tag travel_enquiry_path,{name: "onairdream", id: "onairdream_form", multipart: true} do %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <div class="onairdream-form home-banner-form">
      <h3 style="border-radius: 10px 10px 0px 0px" >Book Domestic &amp; International Flights</h3>
      <div class="col-md-12 select-trip d-flex" style="justify-content: space-around;">
        <p>
          <label class="radio-inline">
            <input id="radio1" type="radio" onclick="show2();" name="trip[trip_type]" checked="" value="Round Trip" style="margin-right: 2px;">Round Trip
          </label>
        </p>
        <p>
          <label class="radio-inline">
            <input id="radio2" type="radio" onclick="show1();" name="trip[trip_type]" value="One Way" style="margin-right: 2px;">One Way
          </label>
        </p>
        <p>
          <label class="radio-inline">
            <input id="radio3" type="radio" onclick="show2();" name="trip[trip_type]" value="Multi City" style="margin-right: 2px;">Multi City
          </label>
        </p>
      </div>

      <div class="col-md-12 d-flex" >
	      <div class="col-md-6 p-1">
	        <div class="form-group">
            <input id="from" name="trip[from]" list="fromCities" class="form-control" placeholder="From*" required="true">
            <datalist id="fromCities">
              <% @source.each do |city| %>
                <option value="<%= city %>">
              <% end  %>
            </datalist>
	          <i class="fa fa-map-marker" aria-hidden="true"></i>
	        </div>
	      </div>
	      <div class="col-md-6 p-1">
	        <div class="form-group">
            <input id="to" name="trip[to]" list="toCities" class="form-control" autocomplete="off" placeholder="To*" type="text" required="true">
            <datalist id="toCities">
              <% @source.each do |city| %>
                <option value="<%= city %>">
              <% end  %>
            </datalist>
	          <i class="fa fa-plane" aria-hidden="true"></i>
	        </div>
	      </div>
      </div>

      <div class="col-md-12 d-flex" >
	      <div class="col-md-6 p-1">
	        <div class="form-group">
            <input type="date" id="departure" name="trip[depart]" placeholder="Departure*" style="padding: 9px 5px;">
	        </div>
	      </div>
	      <div id="div1" class="col-md-6 col-xs-6 p-1">
	        <div class="form-group">
	          <input id="return" name="trip[return]" placeholder="Return*" type="date" style="padding: 9px 5px;">
	        </div>
	      </div>
      </div>

      <div class="col-md-12 d-flex" >
	      <div class="col-md-6 p-1">
	        <div class="form-group">
	          <input id="name" name="trip[name]" placeholder="Name*" type="text" required="true">
	          <i class="fa fa-user" aria-hidden="true"></i>
	        </div>
	      </div>
	      <div class="col-md-6 p-1">
	        <div class="form-group">
	          <input id="mobile" name="trip[mobile]" placeholder="Contact No*" type="tel" class="" required="true">
	          <i class="fa fa-phone" aria-hidden="true"></i>
	        </div>
	      </div>
      </div>

      <div class="col-md-12 col-xs-12 p-1">
        <div class="form-group">
          <input id="email" name="trip[email]" placeholder="Email*" type="email" required="true">
          <i class="fa fa-envelope" aria-hidden="true"></i>
        </div>
      </div>
      <div class="col-md-12 col-xs-12 p-1">
        <div class="form-group mb-0">
          <button class="submit-btn" type="submit" name="Search_Flight">Book Now</button>
        </div>
      </div>

      <div class="security-badge hidden-xs">
        <div class="col-xs-2">
          <img src="<%= asset_path('security-icon.svg') %>" alt="On Air Dream Security">
        </div>
        <div class="col-xs-10">
          <h6>100% SAFE. NO SPAM.</h6>
        </div>
      </div>
    </div>
    <script>
    function show1() {
      document.getElementById('return').disabled = true;
    }

    function show2() {
      document.getElementById('return').disabled = false;
    }
    </script>
  <% end %>
</div>

app/views/application/_footer.html.erb
<!-- ======= Footer ======= -->
<footer id="footer">

  <div class="footer-top">
    <div class="container">
      <div class="row">
        <div class="col footer-links">
          <div class="logo me-auto">
            <h4>
              <a href="/">
                <img style="max-height: 30px;" src="<%= asset_path("onairdream_icon.png") %>" alt="On Air Dream, cheap flights" title="onAirDream">
              </a><span class="footer-logo" >n<span style="color:#fcb839">air</span>dream</span>
            </h4>
          </div>
          <ul>
            <li><a href="#">Terms & Conditions</a></li>
            <li><a href="#">Privacy policy</a></li>
            <li><a href="<%= contact_us_path %>">Contact us</a></li>
            <li><a href="#">About us</a></li>
            <li><a href="#">Cancellation Policy</a></li>
            <li><a href="<%= blogs_path %>">Blogs</a></li>
            <li><a href="#">Disclaimer</a></li>
          </ul>
        </div>

        <div class="col footer-links">
          <h4>Popular destinations</h4>
          <ul>
            <% @destinations.each do |location| %>
              <li><a href="#">Flights to <%= location %></a></li>
            <% end %>
          </ul>
        </div>

        <div class="col footer-links">
          <h4>POPULAR AIRLINES</h4>
          <ul>
            <% @airlines.each do |airline| %>
              <li><a href="#"><%= airline %></a></li>
            <% end %>
          </ul>
        </div>

        <div class="col footer-links">
          <h4>MORE TRAVEL OPTIONS</h4>
          <ul>
            <li><a href="#">Chicago to Hyderabad Flights</a></li>
            <li><a href="#">New York to Delhi Flights</a></li>
            <li><a href="#">Boston to Mumbai Flights</a></li>
            <li><a href="#">San Francisco to Ahmedabad Flights</a></li>
            <li><a href="#">Orlando to Delhi Flights</a></li>
            <li><a href="#">Los Angeles to Hyderabad Flights</a></li>
            <li><a href="#">Chicago to Chennai Flights</a></li>
            <li><a href="#">Houston to Delhi Flights</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container d-md-flex py-4">
    <div class="me-md-auto text-center text-md-start">
      <div class="copyright">
        &copy; Copyright <strong><span>onAirDream</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        Designed by <a href="https://onairdream.com/">onAirDream</a>
      </div>
    </div>
    <div class="social-links text-center text-md-right pt-3 pt-md-0">
      <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
      <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
      <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
      <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
      <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
    </div>
  </div>
</footer><!-- End Footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

app/views/application/_header.html.erb
<!-- ======= Header ======= -->
<header id="header" class="fixed-top d-flex align-items-center">
  <div class="container d-flex align-items-center">

    <div class="logo me-auto">
    	<h1>
				<a href="/">
					<img style="max-height: 55px;" src="<%= asset_path("onairdream_logo.png") %>" alt="On Air Dream, cheap flights" title="onAirDream">
				</a>
			</h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
    </div>

    <nav id="navbar" class="navbar order-last order-lg-0">
      <ul>
        <!-- <li><a class="nav-link scrollto active" href="#hero">Home</a></li> -->
        <li><a class="nav-link scrollto" href="<%= flights_path %>">Flights</a></li>
        <li><a class="nav-link scrollto" href="<%= canada_to_india_path %>"><span class="canada">CANADA</span>-<span class="india">INDIA</span></a></li>
        <li><a class="nav-link scrollto" href="<%= business_class_path %>">Business class</a></li>
        <li><a class="nav-link scrollto" href="<%= last_minute_path %>">Last Minute Deals</a></li>
        <li><a class="nav-link scrollto" href="<%= blogs_path %>">Blog</a></li>
        <li><a  style="color: green;" class="nav-link scrollto" href="<%= win_cash_path %>">Win a Cash!</a></li>
        <li class="call_link" ><i class="blink fa fa-phone-square fa-2x"></i><a class="nav-link scrollto" href="tel:9646612142">+91-9646612142</a></li>
        <!-- <li style="display: flex;align-items: center;" ><i class="bi bi-twitter"></i><a style="padding-left: 0px;" class="nav-link scrollto" href="<%= contact_us_path %>">+91-9646612142</a></li> -->
      </ul>
      <i class="bi bi-list mobile-nav-toggle" onclick="mobile_nav(this)"></i>
    </nav><!-- .navbar -->

<!--     <div class="header-social-links d-flex align-items-center">
      <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
      <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
      <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
      <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
    </div>
 -->

  </div>
</header><!-- End Header -->

<script>
  function mobile_nav(_this){
    document.getElementById('navbar').classList.toggle('navbar-mobile');
    _this.classList.toggle('bi-list');
    _this.classList.toggle('bi-x');
  }
  </script>

app/views/home/blogs.html.erb
<div class="business-class">
	<img src="<%= asset_path('blogs.jpg') %>" alt="On air dream business class flights" width="100%" height="100%">
</div>

<main id="main">
	<section id="business_class" class="">
	  <div class="container">
	  	<div class="row col-md-12">
	  		<h1 class="heading">Blogs <span>Coming Soon!</span></h1>
		  	<div class="col-md-7">
		  		<div class="detail">
		  		</div>
		  	</div>
		  	<div class="col-md-5">
		  	</div>
		  </div>
		</div>
	</section>
</main>

app/views/home/business_class.html.erb
<div class="business-class">
	<img src="<%= asset_path('business-class.jpg') %>" alt="On air dream business class flights" width="100%" height="100%">
</div>
<main id="main">
	<section id="business_class" class="">
	  <div class="container">
	  	<div class="row col-md-12">
	  		<h1 class="heading">Business <span>Class</span></h1>
		  	<div class="col-md-7">
		  		<div class="detail">
		  			<p>
		  				If you are thinking of flying Business Class then you must explore our flight deals.<br>Whether you’re traveling a short distance or long distance, Business Class flights, geared to your comfort and convenience, make long-distance travel a breeze.<br>It will refresh your frayed nerves.
		  			</p><br>

		  			<p>
		  				Our dedicated travel specialists work directly with all major airlines to secure discounts on first and business class flights. No matter where you want to go, we can find business class deals to take you there. How do we do it? Business Class ensures the greatest possible value for your travel by negotiating lower prices on available seats and matching those seats to your schedule and budget for business class tickets.
		  			</p><br>

		  			<p>
		  				No matter the location, our travel professionals can get you there comfortably. We always guarantee an efficient and straightforward process on securing business classflight deals so our travelers’ experience with us is seamless.
		  			</p><br>

		  			<p>
		  				Loosen that tie, recline your seat, and chill with the latest magazine and refreshments from the trolley. Perhaps take in a film or listen to some soothing music from your reclining chair. Our business class deals allow you to take it easy and get some hard-earned rest so that you’re ready to make the best impression upon arrival at your destination. We appreciate that your time is valuable, so we take the stress out of booking, using our knowledge and extensive range of flight options.
		  			</p><br>

		  			<p>
		  				If you are looking for Business Class tickets To India at the lowest price then you have come to the right place. We at Onairdream have the best and most extensive deals on Business Class Flights To India that will comfortably fit within your budget. <br>Onairdream is associated with all the leading airline carriers so we can offer you the best possible experience that you deserve no matter what budget you have.
		  			</p><br>

		  			<p>
		  				Grabbing our Business Class flight deals will not lighten your wallet. In business class, you can fly like royalty. You will get access to the business class lounge, besides being offered drinks, snacks, newspapers and internet facilities. The kind of hospitality you get traveling Business Class is simply breathtaking. Onboard, you will be plied with drinks and delicious meals with exotic wines.
		  			</p>
		  		</div>
		  	</div>

		  	<div class="col-md-5">
		  		<img src="<%= asset_path('business-class-side.jpg') %>" alt="On air dream business class flights" width="100%" height="fit-content">
		  	</div>
	  	</div>
	  </div>
	</section>
</main>

app/views/home/canada_to_india.html.erb
<section id="hero" style="height: 80vh;background: url('<%= asset_path("canada-to-india.jpg") %>') center center;" class="d-flex flex-column justify-content-center align-items-center">
	<%= render 'alerts'%>
	<div class="container">
		<div class="row col-md-12">
			<div class="container text-center text-md-left col-md-5" data-aos="fade-up">
		    <%= render 'enquiry_form'%>
			</div>
			<div class="container text-center text-md-left col-md-7" data-aos="fade-up">
			</div>
		</div>
	</div>
</section>

<main id="main">
	<!-- ======= Portfolio Section ======= -->
	<%= render 'partials/portfolios' %>

	<!-- ======= CheapFlights Section ======= -->
	<section id="business_class" class="">
	  <div class="container">
	  	<div class="row col-md-12">
	  		<h1 class="heading">Cheap Flights <span>Canada to India</span></h1>
	  		<div class="row col-md-12">
	  			<% @canada_cities.each do |city| %>
			  		<div class="col-md-3">
			  			<i class="bx bxs-plane-take-off"></i>
			  			<a href="tel:9646612142" alt="Cheap Flights <%= city %> to India">Flights <%= city.downcase %> to India</a>
			  		</div>
		  		<% end %>
	  		</div>
	  	</div>
		</div>
	</section>
</main>

app/views/home/contact_us.html.erb
<main id="main" style="padding-top: 50px;">
	<!-- ======= Contact Section ======= -->
	<section id="contact" class="contact section-bg">
	  <div class="container">

	    <div class="section-title">
	      <h2>Contact Us</h2>
	      <p>Magnam dolores commodi suscipit eius consequatur ex aliquid fuga</p>
	    </div>

	    <div class="row mt-5 justify-content-center">

	      <div class="col-lg-10">

	        <div class="info-wrap">
	          <div class="row">
	            <div class="col-lg-4 info">
	              <i class="bi bi-geo-alt"></i>
	              <h4>Location:</h4>
	              <p>A108 Adam Street<br>New York, NY 535022</p>
	            </div>

	            <div class="col-lg-4 info mt-4 mt-lg-0">
	              <i class="bi bi-envelope"></i>
	              <h4>Email:</h4>
	              <p>info@example.com<br>contact@example.com</p>
	            </div>

	            <div class="col-lg-4 info mt-4 mt-lg-0">
	              <i class="bi bi-phone"></i>
	              <h4>Call:</h4>
	              <p>+1 5589 55488 51<br>+1 5589 22475 14</p>
	            </div>
	          </div>
	        </div>

	      </div>

	    </div>

	    <div class="row mt-5 justify-content-center">
	      <div class="col-lg-10">
	        <form action="forms/contact.php" method="post" role="form" class="php-email-form">
	          <div class="row">
	            <div class="col-md-6 form-group">
	              <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
	            </div>
	            <div class="col-md-6 form-group mt-3 mt-md-0">
	              <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
	            </div>
	          </div>
	          <div class="form-group mt-3">
	            <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
	          </div>
	          <div class="form-group mt-3">
	            <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
	          </div>
	          <div class="my-3">
	            <div class="loading">Loading</div>
	            <div class="error-message"></div>
	            <div class="sent-message">Your message has been sent. Thank you!</div>
	          </div>
	          <div class="text-center"><button type="submit">Send Message</button></div>
	        </form>
	      </div>

	    </div>

	  </div>
	</section>
</main>

app/views/home/flights.html.erb
<div class="business-class" style="padding-top: 12vh;">
	<img src="<%= asset_path('flights.jpg') %>" alt="On air dream business class flights" width="100%" height="100%">
</div>

<main id="main">
	<section id="business_class" class="">
	  <div class="container">
	  	<div class="row col-md-12">
	  		<h1 class="heading">Flights to <span>India</span></h1>
		  	<div class="col-md-12">
		  		<div class="detail">
		  			<p>
		  				India is a prominent and highly sought-after destination for international tourists. A lot of people from the USA visit India to explore its vibrant culture and rich history. Therefore, flights from the USA to India are in high demand. The first part of planning a trip to India is to look for cheap flight tickets for USA to India international flights that aren’t too heavy on the pockets.OnAirDream helps travelers find affordable flight tickets to destinations from all over the world. If you want to visit India, you can rely on OnAirDream to provide you with the cheapest and affordable flight tickets from USA to India the most reliable options.
		  			</p><br>
		  			<p>
		  				Come and experience India by booking your flights with OnAirDream. You can call us to get the best deals for cheap flights to India. OnAirDream has years of experience and hence can get you the best deal. Book cheap flights to India and get exclusive fares to different locations in your budget. Simply call one of our executives and they will be happy to help you.
		  			</p><br>
		  			<p>
		  				OnAirDream guarantees flights to India at the lowest airfares from USA, be it for a family get-together or tour purposes.We understand the struggles involved in booking USA to India flights, We also provide you one-on-one flight-booking assistance for India to USA flight bookings. Our travel experts are available all throughout the day to help you resolve your queries and doubts regarding USA-India flights. Our payment solutions are also secure and you don’t have to worry a bit before trusting us with your hard-earned money.
		  			</p><br>
		  			<p>
		  				India is a country whose heart beats with a magnificent blend of people, geographies, and traditions. Even after leaving India; the experiences, emotions, and memories will remain forever in your hearts and mind. So, what are you waiting for? Make your reservations on cheap flights to India from USA right away!
		  			</p><br>
		  			<p>
		  				India is a land of culture and immense diversity. Every part of the country has its own magnificence to offer to the visitors. If you wish to explore this country and want to make the most of your trip, you need to have a proper itinerary planned before visiting. USA to India international flights are available to all the major cities of the country, including New Delhi, Mumbai, Chennai, Kochi, Chandigarh , Amritsar, etc.
		  			</p><br>
		  			<p>
		  				You can visit India to explore its breathtaking beauty and geographical wonders. Make it a point to visit various historical sites in the country and learn about its embellished past. A trip to India is going to a life-changing experience since you’ll be immersed in a culture of respect, harmony, and coexistence.
		  			</p>
		  		</div>
		  	</div>
		  </div>
	  	<div class="row col-md-12">
	  		<h1 class="heading">Cheap Flights <span>USA to India</span></h1>
	  		<div class="row col-md-12">
	  			<% ['Atlanta','Chicago','New York','Dallas','Denver', 'Los Angeles','Tempa','San Diego',
	  				'Charlotte','Las Vegas','Phoenix','Orlando','Seattle','Miami','Houston','Fort Lauderdale',
	  				'San Francisco','Minneapolis','Detroit','Boston','Salt Lake City','Philadelphia','Baltimore',
	  				'Nashville','Washington DC','Austin','Portland','St. Louis','San Jose','Oakland','San Antonio',
	  				'Kansas City','Raleigh Durham','Indiana Polis','Cincinnati','Pittsburgh','Bradley'].each do |city| %>
			  		<div class="col-md-3">
			  			<i class="bx bxs-plane-take-off"></i>
			  			<a href="tel:9646612142" alt="Cheap Flights <%= city %> to India">Flights <%= city %> to India</a>
			  		</div>
		  		<% end %>
	  		</div>
	  	</div>
		</div>
	</section>
</main>

app/views/home/index.html.erb
<!-- ======= Hero Section ======= -->
<section id="hero" style="height: 100vh;" class="d-flex flex-column justify-content-center align-items-center">
	<%= render 'alerts'%>
	<div class="container">
		<div class="row col-md-12">
			<div class="container text-center text-md-left col-md-5" data-aos="fade-up">
		    <%= render 'enquiry_form'%>
			</div>
			<div class="container text-center text-md-left col-md-7" data-aos="fade-up">
			  <h1>Save Big on your travel</h1>
			</div>
		</div>
	</div>
</section>
<!-- End Hero -->

<!-- <div class="trustpilot" style="text-align: center;background: #144e88;">
    <img src="<%= asset_path('trustpilot-logo.png') %>" style="margin: 0 auto;text-align: center;display: block;">
    <a style="display: inline-block;margin: 20px 0;color: #fff;text-decoration: underline;" href="https://www.trustpilot.com/review/onairdream.com" target="_blank">View our reviews/ provide your review</a>
</div>
 -->
<main id="main">

	<!-- ======= Portfolio Section ======= -->
	<%= render 'partials/portfolios' %>

	<!-- ======= Why Choose Us Section ======= -->
	<%= render 'partials/why_choose_us' %>

	<!-- ======= Services Section ======= -->
	<%= render 'partials/services' %>

	<!-- ======= About Section ======= -->
	<%= render 'partials/about-section' %>

	<!-- ======= Blogs Section ======= -->
	<%#= render 'partials/blogs' %>


</main><!-- End #main

app/views/home/win_cash.html.erb
<div class="business-class">
	<img src="<%= asset_path('win.jpg') %>" alt="On air dream business class flights" width="100%" height="100%">
</div>

<main id="main">
	<section id="business_class" class="">
	  <div class="container">
	  	<div class="row col-md-12">
	  		<h1 class="heading">Win a Cash <span>Coming Soon!</span></h1>
		  	<div class="col-md-7">
		  		<div class="detail">
		  		</div>
		  	</div>
		  	<div class="col-md-5">
		  	</div>
		  </div>
		</div>
	</section>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnAirDream</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- Favicons -->
    <link href="<%= asset_path("onairdream_icon.png") %>" rel="icon">
    <link href="<%= asset_path("onairdream_icon.png") %>" rel="apple-touch-icon">
    <script src="https://code.iconify.design/2/2.1.1/iconify.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'header'%>
    <%= yield %>
    <%= render 'footer'%>
  </body>
</html>